### ISSUE TITLE
New proposed syntax for defining gestures

### ISSUE THREAD

**Issue by peol** [stoffeastrom/touche#13]
Currently, there's a lot of overhead when defining a gesture. There's object merging for options, default empty callbacks and so on. I'd like to see a cleaner, more easily understood API for defining gestures.

Below is a proposed way of a cleaner API.

``` js
Touche.add('gesturename', {
    options: {},
    init: function() {},
    start: function() {},
    update: function() {},
    end: function() {},
    cancel: function() {}
});
```

`init` is the only required key in the gesture definition. All others (`options`, `start`, `update`, `end`, `cancel`) are optional.
- `options` are defined default values, e.g. thresholds and so on that are specific to the gesture
- `init` handles any logic that should be run when the gesture is bound to an element
- `start` is triggered when the gesture manager of that element deems it appropriate to start the gesture
- `update` is triggered whenever the gesture has been started and there's movement (either by finger, timer, mouse etc.)
- `end` is triggered if the gesture successfully ended, this is what most people would want to use
- `cancel` is triggered if the element's gesture manager has seen another gesture that has been fulfilled or if the user somehow cancelled the interaction (e.g. `touchcancel` or similar)

Let's open up a discussion around this so the API is simple to use.

**Comment by stoffeastrom** [comment]
I agree on that we need to simplify and get a cleaner api! Looks good to me. Maybe we could add some syntactic sugar using chaining.

``` js
Touche.add('gesturename')
    .options({}) //could even implement own setters/gesture .threshold(20)
    .init(function(){})
    .start(function(){})
    .update(function(){})
    .end(function(){})
    .cancel(function(){});
```

**Comment by stoffeastrom** [comment]
When binding a gesture

``` js
var mygesture = Touche.tap(element)
    .options({})
    .start(function(){})
    .update(function(){})
    .end(function(){})
    .cancel(function(){});

//example
mygesture.threhold(30);
```

**Comment by peol** [comment]
Interesting idea. I'm not too fond of having function calls for each, but maybe the majority of users would like it. It just feels like an overhead, I doubt most users will ever re-configure a bound gesture but let's investigate. :)

**Comment by stoffeastrom** [comment]
True. In your definition you call it gesture manager.. maybe we could agree on gesture engine :)?

**Comment by peol** [comment]
But doesn't Engine somehow imply a single instance, an engine that controls everything? The "manager" controls gestures for a specific DOM element (that's the distinction I had in mind anyway) but as long as we use the same terminology (and rename it in the code) I'm fine with either :p

**Comment by stoffeastrom** [comment]
mm let's think about it :P

**Comment by stoffeastrom** [comment]
fixed
