### ISSUE TITLE
on/off, we need a way to do off on an certain gesture instance

### ISSUE THREAD

**Issue by stoffeastrom** [stoffeastrom/touche#14]
For doubletap we do T(elem).on(this) and T(elem).off('tap'). If we only want to do off on a certain gesture we need to make sure to remove the correct instance and not all for the type 'tap'.

**Comment by stoffeastrom** [comment]
One approach could be:
1. Send in a 'id' when binding Touche(element).tap({ id: 'mytapevent1' }); Unbinding would be Touche(element).tap.off('mytapevent1'); .off() would still remove all bound gestures for that element. .off('type') doesn't make sense to support anymore. If you don't care about unbinding just leave the id and Touche will generate one for you. This way we could generate an id in doubletap when binding tap which we can use to unbind.

EDIT: How should we handle if the id is duplicate? Maybe we could add a getId that generates a unique id

var id = Touche(element).getId();
Touche(element).tap({ id: id, ...});

Touche(element).off(id);

**Comment by peol** [comment]
I'd much rather see something like this: `Touche(element).on('tap', { id: myId });` and to unbind `Touche(element).off('tap', myId);`

I would leave the id's completely up to the user. If none is defined, it'll only be unbindable using `.off('tap')`.

**Comment by peol** [comment]
ID's can also be seen as a namespace, so if several `tap`'s has it, they all get removed. Maybe a `.off('*', myId);` syntax would be good to unbind all specific to one scope.

**Comment by stoffeastrom** [comment]
Alright, sounds OK. 

Binding:
Touche(element).tap({ id: myId}); or
Touche(element).on('tap', { id: myID });

Unbinding:

``` js
Touche(element).off( type, myId );
type could be actual type or '*' for all types
myId could be actual Id or undefined
```

So 

``` js
Touche(element).off() -> all gestures for element will be removed
Touche(element).off('tap') -> all gestures of type 'tap' for element will be removed
Touche(element).off( '*', myId) -> all gestures with myId for element will be removed 
```
