### ISSUE TITLE
fix offset calculation in T.utils.getRect

### ISSUE THREAD

**Issue by stoffeastrom** [stoffeastrom/touche#17]

**Comment by peol** [comment]
When's this not working?
I tried programmatically scroll the test index page and all test still passes.

**Comment by stoffeastrom** [comment]
Haven't tested it myself yet but apparently offsetTop, offsetLeft is offset from parent so if you have more than one nested element? So maybe if we add more nested elements for the test..

**Comment by peol** [comment]
Hmm, OK. I'll take a swing at it on sunday.

**Comment by stoffeastrom** [comment]
Doesn't work all the way. We need to use getBoundingClientRect instead
