### ISSUE TITLE
Swipe calculations wrong when using `event.target`

### ISSUE THREAD

**Issue by peol** [stoffeastrom/touche#36]

**Comment by stoffeastrom** [comment]
I guess we should change so all gestures are using the bound element?

Only use case where it wont work is if you bind all gestures on documeny/body. Maybe we should support an option.targetElement or something equivalent?

This way the threshold logic still would work for delegated events

**Comment by stoffeastrom** [comment]
After some more consideration I think the best way is to just use the bound element. If you are using jquery and delegation it's up to you to calculate the correct percentage in your handler.

**Comment by peol** [comment]
Agree, if we could expose a helper that would be great. Maybe...

`Touche.transformData(event.data, event.target)` (event.target being the
element the user wants to transform the data for).
